### ISSUE TITLE
Same number for Transaction ID Modbus TCP

### ISSUE THREAD

**Issue by Dannol0** [Cloud-Automation/node-modbus#309]
Hi,

As the title suggests, is it possible to set the transaction ID of the modbus TCP calls to always be the same?
We would need it to always be at 0 (due to a factory defect of a machine to which we have to integrate).

Thanks for the support, have a nice day.

**Comment by stefanpoeter** [comment]
Hi @Dannol0,

you can always fork this library and change what you need to change. I am sure this is possible. 

In its current form the ID will always be incremented since there could be multiple requests that need to be sorted when returning. If you use the same ID on every request you can only handle one request at a time.
