### ISSUE TITLE
TCP Server no discrete inputs

### ISSUE THREAD

**Issue by GermanBluefox** [Cloud-Automation/node-modbus#58]
Hello! Very good package.
I tried TCP server and found out, that there is no discrete inputs. 
Both files **server/ReadDiscreteInputs.js** and **server/ReadInputRegisters.js** are addressing this.getInput().

I can make pull request for it if you want.

Another extension would be: events for connecting and disconnecting of masters. I can make a pull request for this too.

Greetings,
bluefox

**Comment by BauchBeinePoe** [comment]
There is no direct specification which function code reads from what buffer. According to the specification this is left to the vendor. 

If you want to make a pull request than make it input discrete, coils, input register and holding registers like in the image below.

![bildschirmfoto_2016-10-24_12-48-56](https://cloud.githubusercontent.com/assets/962108/19642997/5490b2f8-99e8-11e6-9cb2-f8ecebc7c047.png)

````
var customServer = stampit()
        .refs({
            'logEnabled' : true,
            'port' : 8888,
            'responseDelay' : 10, 
            discrete : new Buffer(1024),
            coils : new Buffer(1024),
            holding : new Buffer(1024),
            input : new Buffer(1024)
        })
````

I would suggest to publish this into a 2.0.0 release since this conflicts with the current behaviour.
