### ISSUE TITLE
Can the two's complement be decoding incorrectly?

### ISSUE THREAD

**Issue by angieskazka** [Cloud-Automation/node-modbus#62]
Hi! i'm getting data from a modbus device and negative temperatures show up in node.js application as 65413-something. I can fix it by manually post-processing the inputs like this:
```
  var decode = function(x){
    if(x>1000) x = x - 65536; //substract Math.pow(2,16)
    return x;
  }
```
but i wonder if node-modbus already supposed to interpret this correectly on reading the registers. the "two's complement" and so on...

Here is my device i'm reading from 
http://www.comet-america.com/products/temperature-humidity-pressure-transmitters-and-regulators/web-sensor-p8641-with-poe-four-channels-remote-thermometer-hygrometer/reg-P8641#downloadd

in the instruction manual [here](http://www.comet-america.com/userfiles/file/manuals-english/transmitters/ie-snc-P86xx.pdf?time=1478686246&FixForIE=.pdf) page 22 there is a register map (I'm interested in int*10 values):

![image](https://cloud.githubusercontent.com/assets/3648190/20135023/fdc48b60-a66d-11e6-9b92-9ec1063fa49e.png)

**Comment by BauchBeinePoe** [comment]
If I understand this correct, you are wondering how you can get the two-complement interpretation of your temperature? Since @psorowka made a pull request, you are able to read the result from the modbus request out of a buffer. From that you can just `readUInt16` your temperature. Have a look [here](https://nodejs.org/api/buffer.html) for more help.

**Comment by angieskazka** [comment]
thanks @BauchBeinePoe! it helped (of course it did)
